### ISSUE TITLE
key too small

### ISSUE THREAD

**Issue by s1037989** [olegwtf/p5-Mojo-SMTP-Client#11]
I see that there were some attempts made to correct this.  I'm still having this issue with 0.20_2.

How are you generating new cert and key files?

What is the cause?  Newer IO::Socket::SSL?

**Comment by olegwtf** [comment]
As I remember I got it from Mojolicious test suit. Are you able to generate some key that not fails on your side?

**Comment by s1037989** [comment]
No, I haven't been able to get anything working yet. I was hoping you could
share what you were doing and then I'd tried to keep working on it.

**Comment by msusta** [comment]
The issue come about from OpenSSL 1.1 that's being distributed in eg. Debian with stricter requirements about the keys used with certificates [1]

You have a RSA key of 1024 bits which is not enough for the default configuration and as such it will fail. When you generate the key just set it to 2048 bits and it will be fine.

`openssl genrsa -out whatever.key 2048`

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907888

**Comment by olegwtf** [comment]
Is it ok with 0.20 release?

**Comment by s1037989** [comment]
Success on my box, where previously it failed!  Thanks for the updated release!

```
$ cat /etc/issue
Ubuntu 20.04.5 LTS \n \l

$ rm -rf local ; echo 'requires "Mojo::SMTP::Client", "== 0.19";' > cpanfile ; cpanm -L local --installdeps .
Building and testing Mojo-SMTP-Client-0.19 ... FAIL

$ rm -rf local ; echo 'requires "Mojo::SMTP::Client", "== 0.20";' > cpanfile ; cpanm -L local --installdeps .
Successfully installed Mojo-SMTP-Client-0.20
```
