### ISSUE TITLE
Incompatibility with Mojolicious 7.49+

### ISSUE THREAD

**Issue by karel-m** [olegwtf/p5-Mojo-SMTP-Client#7]
There are couple of issues:
* `$delay->catch` has changed
* `$delay->remaining` is deprecated
* Mojo::IOLoop::Delay's `finish` event is deprecated

See Changes https://metacpan.org/changes/release/SRI/Mojolicious-7.55#L25

Quick&dirty hack dealing just with `catch` changes:
```diff
diff --git a/lib/Mojo/SMTP/Client.pm b/lib/Mojo/SMTP/Client.pm
index 1711fec..f19c842 100644
--- a/lib/Mojo/SMTP/Client.pm
+++ b/lib/Mojo/SMTP/Client.pm
@@ -140,8 +140,9 @@ sub send {
        push @steps, $self->_make_cmd_steps(0, @_);

        # non-blocking
-       my $delay = $self->{delay} = Mojo::IOLoop::Delay->new(ioloop => $self->_ioloop)->steps(@steps)->catch(sub {
-               shift->emit(finish => $_[0]);
+       my $delay = $self->{delay} = Mojo::IOLoop::Delay->new(ioloop => $self->_ioloop)->steps(@steps);
+       $delay->catch(sub {
+               $delay->emit(finish => $_[0]);
        });
        $delay->on(finish => sub {
                if ($cb) {
```

However, I am afraid that the proper patch will be a bit more complicated.

**Comment by olegwtf** [comment]
I added your patch to 0.14, to make it work again. The next step is to wait how `Mojo::IOLoop::Delay` will be changed finally and make proper fix.  I'll close this for now. Please open new one when deprecated functionality will be removed, with patch if possible ;)
